scuba_diver_v0: scuba_diver_v0.c
	gcc scuba_diver_v0.c -o scuba_diver_v0

scuba_diver_v1: scuba_diver_v1.c
	gcc scuba_diver_v1.c -o scuba_diver_v1

scuba_diver_v2: scuba_diver_v2.c
	gcc scuba_diver_v2.c -o scuba_diver_v2

scuba_diver_v3: scuba_diver_v3.c
	gcc scuba_diver_v3.c -o scuba_diver_v3
