snappy_v0: snappy_v0.c
	gcc snappy_v0.c -o snappy_v0

snappy_v1: snappy_v1.c
	gcc snappy_v1.c -o snappy_v1

snappy_v2: snappy_v2.c
	gcc snappy_v2.c -o snappy_v2

snappy_v3: snappy_v3.c
	gcc snappy_v3.c -o snappy_v3

snappy_v4: snappy_v4.c
	gcc snappy_v4.c -o snappy_v4
